### ISSUE TITLE
有道的翻译结果显示更详细

### ISSUE THREAD

**Issue by qaqland** [hnmaonanbei/go-youdao-fanyi#1]
如果我翻译`hello`，得到的结果是`你好`
能不能翻译显示更多，就和微信小程序里的显示的一样多，比如翻译 `hello`，显示
> hello
> int. 喂；哈罗，你好，您好（表示问候， 惊奇或唤起注意时的用语）
> n. （Hello）（法）埃洛（人名）
---
感谢&在线等

**Comment by hnmaonanbei** [comment]
ccccpress  感谢你的反馈， 但是对于这种格式返回信息我并没有找到相关的地址， 你是否能够给我提供相应的网址， 谢谢。

**Comment by qaqland** [comment]
![image](https://user-images.githubusercontent.com/62464571/100227794-a82dc280-2f5c-11eb-9a1e-866cdd9a350b.png)

**Comment by hnmaonanbei** [comment]
已经添加完成了, 如果没问题请关闭这个问题

**Comment by hnmaonanbei** [comment]
已经新增了该功能

**Comment by qaqland** [comment]
我使用了您的项目！谢谢
[ccccpress/1book](https://github.com/ccccpress/1book)
